use avian3d::prelude::{Collider, CollisionLayers, RigidBody};
use bevy::prelude::{Bundle, Component, Quat, Resource, Transform, Vec3};
use serde::{Deserialize, Serialize};
use crate::vleue::feature::character::movement::{PLAYER_LAYER, WORLD_LAYER};
// use crate::vleue::feature::level::map::{FLOOR_HEIGHT, FLOOR_WIDTH};

// #[derive(Bundle)]
// pub struct FloorPhysicsBundle {
// 	collider: Collider,
// 	collision_layers: CollisionLayers,
// 	rigid_body: RigidBody,
// }
//
// impl Default for FloorPhysicsBundle {
// 	fn default() -> Self {
// 		Self {
// 			collider: Collider::cuboid(FLOOR_WIDTH, FLOOR_HEIGHT, FLOOR_WIDTH),
// 			collision_layers: CollisionLayers::new(WORLD_LAYER, PLAYER_LAYER),
// 			rigid_body: RigidBody::Static,
// 		}
// 	}
// }


// #[derive(Component)]
// pub struct MapRoot; // Map root node marker, used for cleanup。

#[derive(Component)]
pub struct MapSceneMarker; // Marker for scene instances generated by map config.

#[derive(Component)]
pub struct MapColliderMarker; // Marker for collider instances generated by map config.

#[derive(Component)]
pub struct ReferenceCubeMarker;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct MapEntityConfig {
	pub name: String, // Map instance logical name, for debugging and gameplay semantics.
	#[serde(default)]
	pub poi_id: Option<String>, // Which POI this scene instance belongs to, for gameplay system association.
	pub glb_path: String, // glb asset path, relative to game/assets.
	#[serde(default)]
	pub scene: usize, // Scene index in glb, defaults to Scene0.
	pub position: [f32; 3], // World coordinates.
	#[serde(default = "default_rotation")]
	pub rotation: [f32; 4], // Quaternion xyzw.
	#[serde(default = "default_scale")]
	pub scale: [f32; 3], // Model scale.
	#[serde(default)]
	pub collider_size: Option<[f32; 3]>, // Optional simple box collision, used for occlusion culling.
}

#[derive(Resource, Clone, Debug, Default, Deserialize, Serialize)]
pub struct MapLayout {
	#[serde(default)]
	pub map: MapMetaConfig,
	#[serde(default)]
	pub poi: Vec<PoiConfig>,
	#[serde(default)]
	pub routes: Vec<RouteConfig>,
	#[serde(default)]
	pub extraction_points: Vec<ExtractionPointConfig>,
	#[serde(default)]
	pub miasma: MiasmaConfig,
	#[serde(default)]
	pub entities: Vec<MapEntityConfig>,
}

impl MapEntityConfig {
	pub fn position_vec3(&self) -> Vec3 { Vec3::from_array(self.position) }

	pub fn rotation_quat(&self) -> Quat {
		Quat::from_xyzw(self.rotation[0], self.rotation[1], self.rotation[2], self.rotation[3])
	}

	pub fn scale_vec3(&self) -> Vec3 { Vec3::from_array(self.scale) }

	pub fn scene_asset_path(&self) -> String { format!("{}#Scene{}", self.glb_path, self.scene) }

	pub fn transform(&self) -> Transform {
		Transform::from_translation(self.position_vec3()).with_rotation(self.rotation_quat()).with_scale(self.scale_vec3())
	}
}

const fn default_rotation() -> [f32; 4] { [0.0, 0.0, 0.0, 1.0] }

const fn default_scale() -> [f32; 3] { [1.0, 1.0, 1.0] }

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct MapMetaConfig {
	#[serde(default)]
	pub id: String, // Map unique identifier.
	#[serde(default)]
	pub display_name: String, // Map display name.
	#[serde(default)]
	pub size: [f32; 2], // Map plane size, for minimap and shrinking circle.
	#[serde(default)]
	pub origin: [f32; 3], // World origin offset.
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct PoiConfig {
	pub id: String, // POI logical id, for paths, entities and events reuse.
	pub display_name: String, // Frontend display name.
	#[serde(default)]
	pub tier: u8, // Hotspot tier, corresponds to star rating on map.
	pub center: [f32; 3], // POI center point, for minimap and area judgment.
	#[serde(default)]
	pub radius: f32, // Rough radius, for circular area quick judgment.
	#[serde(default)]
	pub layer: String, // Ground layer / Underground middle layer / Underground mine layer.
	#[serde(default)]
	pub tags: Vec<String>, // e.g. castle/forest/port/forge.
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct RouteConfig {
	pub id: String, // Route logical id.
	pub from_poi: String, // Starting POI.
	pub to_poi: String, // Ending POI.
	#[serde(default)]
	pub layer: String, // Which layer this route is on.
	#[serde(default)]
	pub route_kind: String, // road / tunnel / rail / zipline / shortcut。
	#[serde(default)]
	pub control_points: Vec<[f32; 3]>, // Route polyline points.
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ExtractionPointConfig {
	pub id: String, // Extraction point logical id.
	#[serde(default)]
	pub poi_id: Option<String>, // Which POI this belongs to.
	pub position: [f32; 3], // Extraction point position.
	#[serde(default)]
	pub radius: f32, // Extraction trigger radius.
	#[serde(default)]
	pub required_item: Option<String>, // Required extraction item logical name.
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct MiasmaConfig {
	#[serde(default)]
	pub origin: [f32; 3], // Miasma initial center.
	#[serde(default)]
	pub start_delay_secs: f32, // How long to wait before first spread.
	#[serde(default)]
	pub tick_secs: f32, // Each round spread tick.
	#[serde(default)]
	pub start_radius: f32, // Initial radius.
	#[serde(default)]
	pub max_radius: f32, // Final radius.
}
